const ACTIONS = {
  LOGIN: 'LOGIN',
  GET_TOKEN: 'GET_TOKEN',
  GET_USER: 'GET_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_SETTINGS_REQUEST: 'GET_SETTINGS_REQUEST',
  GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
  GET_SETTINGS_FAILED: 'GET_SETTINGS_FAILED',
};

export default ACTIONS;
