# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  berlin-doener-obernkirchen:
    runs-on: [self-hosted, berlin-doener-obernkirchen.de]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: cp "/home/admin/.env" "/home/admin/actions-runner/hsnbgWorkFolder/Heisenberg/Heisenberg"
      - run: pm2 start server

  hsnbg-de:
    runs-on: [self-hosted, hsnbg.de]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: cp "/home/admin/.env" "/home/admin/actions-runner/hsnbgWorkFolder/Heisenberg/Heisenberg"
      - run: pm2 start server
